#!/usr/bin/env bash
# Configurs Nginx server to have custom 404 page
   # contains the string Ceci n'est pas une page
# returns an HTTP 404 error code

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Holberton School' > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtub\
e.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default
service nginx start
