#!/usr/bin/env bash
# Bash script to configure Nginx installation to listen on port 80

apt-get update
apt-get -y install curl
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
