#!/usr/bin/env bash
# creates a file, displays a string indefinitely, deletes the file at end

sudo bash -c "echo $$ >> /var/run/holbertonscript.pid"
trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid' SIGQUIT

while true
do
  echo "To infinity and beyond"
  sleep 2
done
