#!/usr/bin/env bash

i=1
while (( i<=100 )); do
    if ! (( i%15 )); then
	echo FizzBuzz
    elif ! (( i%3 )); then
	echo Fizz
    elif ! (( i%5 )); then
	echo Buzz
    else
	echo $i
    fi
    let i++
done
