#!/usr/bin/env bash
#displays numbers from 1 to 100 with classic fizzbuzz exceptions
i=1
while (( i<=100 )); do
    if ! (( i%15 )); then
	echo FizzBuzz
    elif ! (( i%3 )); then
	echo Fizz
    elif ! (( i%5 )); then
	echo Buzz
    else
	echo $i
    fi
    let i++
done
