#!/usr/bin/env bash

input="/etc/passwd"
IFS=:
while read -r one two three four five six seven
do
    echo "The user $one is part of the $four gang, lives in $six and rides $seven. $four's place is protected by the passcode $two, more info about the user here: $five"
done < "$input"
